### ISSUE TITLE
0.4.4 tests fail in PyPy

### ISSUE THREAD

**Issue by isuruf** [flintlib/python-flint#74]
```
test_fmpz...Error in test_fmpz
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/python-flint_1694094201440/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/pypy3.9/site-packages/flint/test/__main__.py", line 36, in run_tests
    test()
  File "/home/conda/feedstock_root/build_artifacts/python-flint_1694094201440/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/pypy3.9/site-packages/flint/test/test.py", line 141, in test_fmpz
    assert pow(a, flint.fmpz(b), c) == ab_mod_c
TypeError: operands do not support pow()
```

This used to work in 0.4.2

**Comment by oscarbenjamin** [comment]
I haven't tested with PyPy at all. What version of PyPy are you using for this?

**Comment by isuruf** [comment]
PyPy3.9 7.3.12

**Comment by oscarbenjamin** [comment]
> PyPy3.9 7.3.12

The tests all passed for me locally with PyPy3.9 7.3.11.

**Comment by oscarbenjamin** [comment]
I tried reproducing this in CI in #76 but the wheel build fails under PyPy.

**Comment by oscarbenjamin** [comment]
> the wheel build fails under PyPy.

```
  + python -m pip wheel /Users/runner/work/python-flint/python-flint --wheel-dir=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/built_wheel --no-deps
  Processing /Users/runner/work/python-flint/python-flint
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [16 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/Users/runner/work/python-flint/python-flint/setup.py", line 9, in <module>
            from numpy.distutils.system_info import default_include_dirs, default_lib_dirs
          File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/build/venv/lib/pypy3.9/site-packages/numpy/__init__.py", line 139, in <module>
            from . import core
          File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/build/venv/lib/pypy3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
            from . import multiarray
          File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/build/venv/lib/pypy3.9/site-packages/numpy/core/multiarray.py", line 86, in <module>
            def empty_like(prototype, dtype=None, order=None, subok=None, shape=None):
          File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/build/venv/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 178, in decorator
            return array_function_dispatch(
          File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-ck51u289/pp39-macosx_x86_64/build/venv/lib/pypy3.9/site-packages/numpy/core/overrides.py", line 160, in decorator
            public_api = _ArrayFunctionDispatcher(dispatcher, implementation)
        AttributeError: 'builtin_function_or_method' object has no attribute '__qualname__'
```

**Comment by oscarbenjamin** [comment]
> > PyPy3.9 7.3.12
> 
> The tests all passed for me locally with PyPy3.9 7.3.11.

I'm a bit stuck here without being able to reproduce this.

**Comment by isuruf** [comment]
Do you have a local conda installation? If so, I can give instructions on how to reproduce, else I can try to set  it up on CI.

Note that the tests fail on all three OSes at https://github.com/conda-forge/python-flint-feedstock/pull/31

**Comment by oscarbenjamin** [comment]
I don't even want to try to fix this until we have CI that can reproduce the problem. If we don't test PyPy in CI then I would rather just say that it is not supported.

**Comment by oscarbenjamin** [comment]
I have just tested locally that I can build a wheel and install from it and all tests are passing.

This is with pypy-3.9-7.3.11 which is the newest version available from pyenv.

If the difference is pypy-3.9-7.3.12 rather than 7.3.11 then that might indicate a PyPy bug rather than a python-flint bug.

The PRs to python-flint in between 0.4.2 and 0.4.4 are:

- #61 
- #63 
- #65 
- #69 
- #71 

They are all just refactoring or unrelated changes.

The bug reported is with 3-arg pow like:
```python
pow(1, flint.fmpz(2), 3)
```
This is the code for fmpz.__pow__ in 0.4.2:
https://github.com/flintlib/python-flint/blob/b658fd3e3e8f11be228c484d1b7b200c71e60492/src/flint/fmpz.pyx#L365-L412
This is the code in 0.4.4:
https://github.com/flintlib/python-flint/blob/24267a5ebc16a176299d178641ba6f61313f4fa7/src/flint/types/fmpz.pyx#L358-L405
So unless I've missed something the code for `fmpz.__pow__` is unchanged although there was a refactor that moved it to a different file.

The code still passes under CPython in any case.

**Comment by isuruf** [comment]
> If the difference is pypy-3.9-7.3.12 rather than 7.3.11 then that might indicate a PyPy bug rather than a python-flint bug.

I checked with 7.3.11 in conda and the bug is still there

**Comment by oscarbenjamin** [comment]
Is there an associated PyPy bug report for this?

**Comment by oscarbenjamin** [comment]
gh-93 fixes a bug to do with 3-arg pow but I am not sure if it is related to the bug here.

**Comment by oscarbenjamin** [comment]
I'm not sure how easy it is to support the 3-arg pow under PyPy. The mechanism that makes it work in CPython is quite obscure and only works from Cython (not pure Python):
https://discuss.python.org/t/awkward-dunders-for-pow-x-y-z/35185

I can reproduce this locally now and also there is a new test failure under PyPy:
```
test_polys...Error in test_polys
Traceback (most recent call last):
  File "/home/oscar/current/active/python-flint/src/flint/test/__main__.py", line 36, in run_tests
    test()
  File "/home/oscar/current/active/python-flint/src/flint/test/test.py", line 2362, in test_polys
    assert raises(lambda: P([1, 2, 1]) // 0, ZeroDivisionError)
  File "/home/oscar/current/active/python-flint/src/flint/test/test.py", line 18, in raises
    f()
  File "/home/oscar/current/active/python-flint/src/flint/test/test.py", line 2362, in <lambda>
    assert raises(lambda: P([1, 2, 1]) // 0, ZeroDivisionError)
  File "src/flint/types/fmpz_mod_poly.pyx", line 522, in flint.types.fmpz_mod_poly.fmpz_mod_poly.__floordiv__
    return fmpz_mod_poly._floordiv_(self, other)
  File "src/flint/types/fmpz_mod_poly.pyx", line 512, in flint.types.fmpz_mod_poly.fmpz_mod_poly._floordiv_
    if not right.leading_coefficient().is_unit():
  File "src/flint/types/fmpz_mod_poly.pyx", line 892, in flint.types.fmpz_mod_poly.fmpz_mod_poly.leading_coefficient
    return self[self.degree()]
IndexError: %T index out of range
```

**Comment by oscarbenjamin** [comment]
I haven't been able to set this up but does gmpy2 manage to do the 3-arg pow under PyPy?

Under CPython it works just like python-flint does:
```python
>>> import gmpy2
>>> pow(2, gmpy2.mpz(3), 4)
mpz(0)
```
This is what fails for python-flint under PyPy:
```python
>>>> import flint
>>>> pow(2, flint.fmpz(3), 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: operands do not support pow()
```

**Comment by oscarbenjamin** [comment]
> I'm not sure how easy it is to support the 3-arg pow under PyPy.

I think that we just have to add an exception for this in the test suite. Either PyPy and CPython need to find a compatible way of supporting the overload of 3-arg pow or it just is not possible to make this work under PyPy.

Another possibility would be to just make it always a TypeError to do e.g. `pow(int, fmpz, int)` so that behaviour is at least consistent across PyPy and CPython.

**Comment by oscarbenjamin** [comment]
> there is a new test failure under PyPy:

This needs investigating before releasing 0.5.0.

**Comment by oscarbenjamin** [comment]
The new test failure is basically this:
```python
In [14]: p = flint.fmpz_mod_poly_ctx(3)(0)

In [15]: p
Out[15]: 0

In [16]: p.leading_coefficient()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[16], line 1
----> 1 p.leading_coefficient()

File ~/current/active/python-flint/src/flint/types/fmpz_mod_poly.pyx:893, in flint.types.fmpz_mod_poly.fmpz_mod_poly.leading_coefficient()
    891         fmpz_mod(3, 163)
    892     """
--> 893     return self[self.degree()]
    894 
    895 def reverse(self, degree=None):

IndexError: %T index out of range
```
Running the python code shown in the traceback gives:
```python
In [18]: p.degree()
Out[18]: -1

In [19]: p[-1]
Out[19]: fmpz_mod(0, 3)

In [17]: p[p.degree()]
Out[17]: fmpz_mod(0, 3)
```
So `p[p.degree()]` works but the `leading_coefficient` method that does `self[self.degree()]` fails.

This is either a Cython bug or a PyPy bug. Minimal reproducer without python-flint:
```cython
# polymod.pyx

cdef class poly:

    def __len__(self):
        return 0

    cpdef long degree(self):
        return -1

    def __getitem__(self, key):
        if key < 0:
            return 0

    def leading_coefficient(self):
        return self[self.degree()]
```
Then under PyPy:
```python
>>>> import polymod
>>>> p = polymod.poly()
>>>> print(p.degree())
-1
>>>> print(p[-1])
0
>>>> print(p[p.degree()])
0
>>>> print(p.leading_coefficient())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "polymod.pyx", line 14, in polymod.poly.leading_coefficient
    return self[self.degree()]
IndexError: %T index out of range
```

**Comment by skirpichev** [comment]
@oscarbenjamin, I opened https://github.com/pypy/pypy/issues/5207, that seems to be relevant for this issue.  But now this looks more as a CPython issue.
